//! best_belief — ε-quantile Beta lower bound for conservative selection.
//!
//! Distilled from the Red Queen Gödel Machine (Iacob et al., arXiv:2606.26294
//! §3.5 + App. F Prop. 4). Modelless analog of RQGM's best-belief selection
//! rule. Used to decide which frozen snapshot / archetype blend shard / zone
//! geometry pod to promote — decisions under bounded evidence where
//! conservatism (a lower bound, not a point estimate) is the right risk
//! posture.
//!
//! Complements [`sample_beta`](crate::) Thompson sampling (EXPLORATION) with
//! a conservative EXPLOITATION / SELECTION counterpart: Thompson draws a
//! random sample from Beta(1+S, 1+F) for exploration; `best_belief_score`
//! returns the ε-quantile lower bound `I⁻¹_ε(1+S, 1+F)` for exploitation.
//!
//! # The primitive
//!
//! `BB_ε(S, F) = I⁻¹_ε(1 + S, 1 + F)` — the value the candidate's true utility
//! exceeds with probability `1 − ε` under the Beta-Bernoulli working posterior
//! (RQGM Prop. 4). Lower ε ⇒ more conservative. The classic choice is ε = 0.05.
//!
//! # Algorithm
//!
//! **Hot path** (the common selection regime `S, F ∈ [0, 31]` at one of the
//! five standard ε values `{0.01, 0.05, 0.1, 0.25, 0.5}`): direct O(1) lookup
//! into a lazily-initialized 32×32×5 table (≈ 20 KB). Bit-identical to the
//! closed-form because the table is generated by the closed-form at first
//! call. Target: a few ns.
//!
//! **Cold path** (large `S+F`, or non-standard ε): inverse regularized
//! incomplete Beta `I⁻¹_ε(a, b)` via Newton iteration on the forward
//! `I_x(a, b)` (Numerical Recipes §6.4 continued-fraction / Lentz). Initial
//! guess is the Wilson-Hilferty-style normal approximation of the Beta
//! quantile using the posterior mean `μ = a/(a+b)`, variance
//! `σ² = ab/((a+b)²(a+b+1))`, and Acklam's rational approximation for `Φ⁻¹(ε)`.
//!
//! Domain is always `a, b ≥ 1` (because of the `+1` pseudocount), so we are
//! always in the well-behaved region — no AS 109 reflection logic for `a < 1`
//! or `b < 1` is needed.
//!
//! # LUT design rationale
//!
//! The Lentz continued fraction is `O(a+b)` iterations to converge, so the
//! closed-form scales linearly with `S+F`. For the intended consumers (freeze/
//! thaw selection, archetype-shard promotion, zone-cache promotion), the
//! evidence counts are bounded by the promotion budget — typically `S+F < 64`.
//! The 32×32 LUT covers that whole regime at the five ε values callers
//! actually use, turning the hot path into a single indexed array read.
//! Off-grid counts or ε values fall back to the closed-form (still correct,
//! just slower).
//!
//! # Allocation discipline (G4)
//!
//! The hot path is allocation-free by construction:
//! - [`best_belief_score`] takes `(u32, u32, f32)` by value and returns `f32`.
//!   Its body calls only `f32` libm intrinsics (`ln`, `exp`, `sqrt`, `abs`)
//!   and stack-local arithmetic. No `Vec`, `Box`, `String`, `format!`,
//!   `to_string`, or collecting iterator appears.
//! - [`select_best_belief`] iterates `&[(u32, u32)]` by reference and returns
//!   `usize`. Same constraints.
//! - [`best_belief_scores`] is the **only** allocating function and is the
//!   documented diagnostic helper — do NOT call it on the hot path.
//!
//! See: `katgpt-rs/.research/320_Red_Queen_Godel_Machine_Selective_Erasure_Best_Belief.md`
//! See: `katgpt-rs/.plans/336_controlled_utility_primitives.md`

// ──────────────────────────────────────────────────────────────────────────
// Tunables
// ──────────────────────────────────────────────────────────────────────────

/// Clamp lower bound for `x` to keep `ln(x)` finite. f32 has ~7 sig digits,
/// so 1e-6 leaves headroom without wasting dynamic range.
const X_MIN: f32 = 1e-6;
/// Symmetric upper clamp.
const X_MAX: f32 = 1.0 - 1e-6;
/// Epsilon floor: `epsilon` is clamped to at least this to avoid div-by-zero
/// in the normal-approximation step / degenerate Beta(1,1) case.
const EPS_MIN: f32 = 1e-7;
/// Convergence target for `|I_x(a,b) - ε|`.
const TOL: f32 = 1e-7;
/// Max Newton iterations. 8 is generous for f32 precision (typically ≤ 4).
const MAX_ITERS: usize = 8;
/// Max continued-fraction iterations for the forward `I_x(a, b)`.
const MAX_CF: usize = 200;
/// CF convergence threshold (Lentz). f32-relative.
const CF_TOL: f32 = 3e-7;
/// Tiny value used as the Lentz "zero denominator" guard.
const CF_TINY: f32 = 1e-30;

// ──────────────────────────────────────────────────────────────────────────
// LUT fast path (Plan 336 G2 unblock)
// ──────────────────────────────────────────────────────────────────────────
// The closed-form I⁻¹_ε(a, b) is O(a+b) because the Lentz continued fraction
// converges in O(a+b) iterations. For the common selection regime (small
// (S,F), standard ε) we precompute the answer into a flat table on first call
// and read it back at a few-ns cost. 32×32 covers the entire freeze/thaw /
// shard-promotion evidence regime; anything larger falls back to the closed
// form. The five ε values are the ones the rest of the codebase (PrudentBanker,
// SafePhased, RQGM §3.5 promotion gate) standardizes on.

/// Max `S` covered by the LUT (exclusive bound — valid indices are `0..LUT_S`).
const LUT_S: usize = 32;
/// Max `F` covered by the LUT (exclusive bound).
const LUT_F: usize = 32;
/// The five standard ε values, in the order they appear in the LUT's first axis.
const LUT_EPS: [f32; 5] = [0.01, 0.05, 0.1, 0.25, 0.5];
/// Total table size: 32 × 32 × 5 = 5_120 f32 entries = 20_480 bytes ≈ 20 KB.
/// Stored as `[eps][s][f]` for direct indexed reads with no arithmetic.
type LutTable = [[[f32; LUT_F]; LUT_S]; 5];

static LUT: std::sync::OnceLock<LutTable> = std::sync::OnceLock::new();

/// Build the LUT by calling the closed form for every `(eps, S, F)` triple.
/// One-time cost: ~5_120 × ~500 ns ≈ 2.5 ms on first call. After init, every
/// subsequent lookup is a single indexed array read.
fn build_lut() -> LutTable {
    let mut table = [[[0.0_f32; LUT_F]; LUT_S]; 5];
    for (e, &eps) in LUT_EPS.iter().enumerate() {
        for s in 0..LUT_S {
            for f in 0..LUT_F {
                table[e][s][f] = best_belief_score_cf(s as u32, f as u32, eps);
            }
        }
    }
    table
}

/// O(1) LUT lookup. Returns `None` if `(S, F, ε)` is outside the LUT's domain
/// (so the caller falls back to the closed form). The `epsilon` match is a
/// bit-exact f32 compare against the five standard values; non-standard ε
/// values fall back to the closed form.
#[inline]
fn lut_lookup(successes: u32, failures: u32, epsilon: f32) -> Option<f32> {
    // Bit-exact match against the standard ε values — bit patterns are stable
    // for these constants, so a `match` on the bits is safe and branch-light.
    let eps_idx: usize = if epsilon == 0.01 {
        0
    } else if epsilon == 0.05 {
        1
    } else if epsilon == 0.1 {
        2
    } else if epsilon == 0.25 {
        3
    } else if epsilon == 0.5 {
        4
    } else {
        return None;
    };
    let s = successes as usize;
    let f = failures as usize;
    if s >= LUT_S || f >= LUT_F {
        return None;
    }
    // `get_or_init` is a single relaxed load + compare after the first call;
    // the branch predictor learns it immediately. We must not call
    // `best_belief_score` (only `best_belief_score_cf`) inside `build_lut`,
    // or we'd recurse through the LUT lookup before the LUT is populated.
    let lut = LUT.get_or_init(build_lut);
    Some(lut[eps_idx][s][f])
}

// ──────────────────────────────────────────────────────────────────────────
// Public API
// ──────────────────────────────────────────────────────────────────────────

/// ε-quantile of `Beta(1 + successes, 1 + failures)` — the conservative lower
/// bound the candidate's true utility exceeds with probability `1 − ε` under
/// the working posterior (RQGM Prop. 4).
///
/// Returns a value in `(0, 1)`. Lower `epsilon` = more conservative.
///
/// - `successes`, `failures` are non-negative Beta-Bernoulli counts (S, F).
/// - `epsilon` ∈ `(0, 1)`, typically `0.05`.
///
/// Allocation-free, branch-light. Target: a few ns on the LUT hot path
/// (`S, F ∈ [0, 31]`, standard ε); falls back to the closed form otherwise.
#[inline]
pub fn best_belief_score(successes: u32, failures: u32, epsilon: f32) -> f32 {
    // ── Edge cases ────────────────────────────────────────────────────────
    // Uniform prior Beta(1, 1) = Uniform(0, 1); the ε-quantile is ε itself.
    // (The "lower bound the utility exceeds with prob 1−ε" IS ε here, since
    //  P(X > ε) = 1 − ε for X ~ Uniform(0,1). The plan's draft text said
    //  "1 − ε" for this case; that's the upper-tail complement — we follow
    //  the standard ε-quantile definition, matching statrs and the unit test
    //  `best_belief_score_uniform_prior`. A caller wanting the upper-tail
    //  value passes `epsilon = 1 − desired`.)
    if successes == 0 && failures == 0 {
        return epsilon.clamp(EPS_MIN, 1.0 - EPS_MIN);
    }
    // ε ≤ 0 → ~0.0 (candidate never selected); ε ≥ 1 → ~1.0 (always selected).
    // Handle directly to avoid driving Newton into the f32-precision-noise
    // floor of the extreme Beta tails.
    if epsilon <= 0.0 {
        return X_MIN;
    }
    if epsilon >= 1.0 {
        return X_MAX;
    }

    // ── Hot path: LUT ─────────────────────────────────────────────────────
    if let Some(v) = lut_lookup(successes, failures, epsilon) {
        return v;
    }

    // ── Cold path: closed form ────────────────────────────────────────────
    best_belief_score_cf(successes, failures, epsilon)
}

/// Closed-form inverse regularized incomplete Beta — the cold path. Called
/// directly only when `(S, F, ε)` is outside the LUT domain (large `S+F` or
/// non-standard ε), and used by `build_lut` to populate the table.
///
/// Kept `pub(crate)` so the LUT builder and any future diagnostic / test can
/// call it directly without going through the LUT.
#[inline]
pub(crate) fn best_belief_score_cf(successes: u32, failures: u32, epsilon: f32) -> f32 {
    // Edge case: S=F=0 → Beta(1, 1) = Uniform(0, 1); the ε-quantile is ε
    // itself. Handled here too (not just in the public wrapper) so that
    // `build_lut` produces bit-identical values to the public API for every
    // cell, including the (0, 0) corner. The Newton path below would converge
    // to ≈ε but not bit-exactly, which would break the LUT/closed-form
    // identity contract.
    if successes == 0 && failures == 0 {
        return epsilon.clamp(EPS_MIN, 1.0 - EPS_MIN);
    }
    debug_assert!(epsilon > 0.0 && epsilon < 1.0, "epsilon range handled by caller");

    let eps = epsilon;
    let a: f32 = 1.0 + successes as f32;
    let b: f32 = 1.0 + failures as f32;

    // ── Initial guess: normal approximation to the Beta quantile ──────────
    let sum = a + b;
    let mu = a / sum;
    let var = (a * b) / (sum * sum * (sum + 1.0));
    let sigma = var.sqrt();
    // Acklam's inverse-normal of `eps`.
    let z = inv_normal_cdf(eps);
    let mut x = mu + sigma * z;
    if !x.is_finite() || x <= 0.0 || x >= 1.0 {
        x = mu; // Degenerate — fall back to the mean; Newton will fix it.
    }
    x = x.clamp(X_MIN, X_MAX);

    // ── Newton iteration ──────────────────────────────────────────────────
    // x_{n+1} = x_n - (I_x(a,b) - ε) / pdf_beta(x; a, b)
    let ln_beta = lbeta(a, b); // ln B(a, b)
    for _ in 0..MAX_ITERS {
        let pdf = beta_pdf_ln(x, a, b, ln_beta);
        if pdf <= 0.0 || !pdf.is_finite() {
            // pdf underflowed — x is in an extreme tail. Bisection fallback.
            return newton_or_bisect(a, b, eps, x, ln_beta);
        }
        let cdf = reg_inc_beta(x, a, b, ln_beta);
        let f_val = cdf - eps;
        if f_val.abs() < TOL {
            return x.clamp(X_MIN, X_MAX);
        }
        let step = f_val / pdf;
        let x_new = x - step;
        if !x_new.is_finite() || x_new <= 0.0 || x_new >= 1.0 {
            // Stepped out of (0, 1). Fall back to bisection on the last good
            // bracket to guarantee convergence.
            return newton_or_bisect(a, b, eps, x, ln_beta);
        }
        x = x_new;
    }
    x.clamp(X_MIN, X_MAX)
}

/// Select the candidate with the highest [`best_belief_score`].
///
/// Ties favor `incumbent_idx` (if provided and within range) to avoid
/// unnecessary snapshot swaps and the cache invalidation they trigger.
///
/// Returns the index into `candidates` of the winner. If `candidates` is
/// empty, **panics** (caller bug — selection over zero candidates is undefined).
/// If `incumbent_idx` is `None` or out of range, pure argmax is used.
///
/// Allocation-free: iterates `&[(u32, u32)]`. Target: ≤ 500 ns on 8 candidates.
#[inline]
pub fn select_best_belief(
    candidates: &[(u32, u32)],
    epsilon: f32,
    incumbent_idx: Option<usize>,
) -> usize {
    assert!(
        !candidates.is_empty(),
        "select_best_belief: empty candidate slice (caller bug)"
    );

    let mut best_idx: usize = 0;
    let mut best_score: f32 = best_belief_score(candidates[0].0, candidates[0].1, epsilon);

    for (i, &(s, f)) in candidates.iter().enumerate().skip(1) {
        let score = best_belief_score(s, f, epsilon);
        // Strict `>` so that the *first* (lowest-index) max wins on a tie.
        // We then apply the incumbent preference below.
        if score > best_score {
            best_score = score;
            best_idx = i;
        }
    }

    // Incumbent tie preference: if the incumbent is in range and its score
    // ties the winner, return the incumbent to avoid churn.
    if let Some(inc) = incumbent_idx {
        if inc < candidates.len() && inc != best_idx {
            let inc_score = best_belief_score(candidates[inc].0, candidates[inc].1, epsilon);
            // Tie = within ULP-level tolerance. f32 equality is fine here
            // because the same deterministic computation produces the same
            // bits; but use <= best_score to be robust to any reordering.
            if inc_score >= best_score {
                return inc;
            }
        }
    }

    best_idx
}

/// Diagnostic helper: score every candidate. Returns a `Vec<f32>` of the same
/// length as `candidates`.
///
/// **Allocates** — do NOT use on the hot path. Provided for logging, audits,
/// and tests where per-candidate transparency matters more than latency.
#[inline]
pub fn best_belief_scores(candidates: &[(u32, u32)], epsilon: f32) -> Vec<f32> {
    candidates
        .iter()
        .map(|&(s, f)| best_belief_score(s, f, epsilon))
        .collect()
}

// ──────────────────────────────────────────────────────────────────────────
// Internal math
// ──────────────────────────────────────────────────────────────────────────

/// `ln B(a, b) = ln Γ(a) + ln Γ(b) − ln Γ(a+b)` via [`ln_gamma`].
#[inline]
fn lbeta(a: f32, b: f32) -> f32 {
    // Rust std does NOT expose `lgamma` on f32/f64. We roll our own Lanczos
    // approximation (see [`ln_gamma`]) and run it in f64 — the result feeds an
    // `exp`, so f64 precision is the right call here.
    let la = ln_gamma(a as f64);
    let lb = ln_gamma(b as f64);
    let lab = ln_gamma((a + b) as f64);
    (la + lb - lab) as f32
}

/// Lanczos approximation of `ln Γ(x)` for `x > 0`. Uses g=7, n=9 coefficients
/// (standard Winitzki / Numerical Recipes set) giving ~1e-15 f64 accuracy.
///
/// Our domain is always `a, b ≥ 1` (the `+1` pseudocount), so the `x < 0.5`
/// reflection branch is dead code in practice — kept only for safety.
#[inline]
fn ln_gamma(x: f64) -> f64 {
    const G: f64 = 7.0;
    const C: [f64; 9] = [
        0.99999999999980993,
        676.5203681218851,
        -1259.1392167224028,
        771.32342877765313,
        -176.61502916214059,
        12.507343278686905,
        -0.13857109526572012,
        9.9843695780195716e-6,
        1.5056327351493116e-7,
    ];
    if x < 0.5 {
        // Reflection: Γ(x)Γ(1-x) = π / sin(πx).
        let pi = std::f64::consts::PI;
        return (pi / (pi * x).sin().abs()).ln() - ln_gamma(1.0 - x);
    }
    let z = x - 1.0;
    let mut a = C[0];
    for i in 1..9 {
        a += C[i] / (z + i as f64);
    }
    let t = z + G + 0.5;
    0.5 * (2.0 * std::f64::consts::PI).ln() + (z + 0.5) * t.ln() - t + a.ln()
}

/// Beta pdf at `x`, given precomputed `ln_beta = ln B(a, b)`.
/// Returns the **actual pdf** (not log-pdf), clamped to ≥ 0.
#[inline]
fn beta_pdf_ln(x: f32, a: f32, b: f32, ln_beta: f32) -> f32 {
    // pdf = x^{a-1} (1-x)^{b-1} / B(a, b)
    // ln pdf = (a-1) ln x + (b-1) ln(1-x) - ln_beta
    let ln_x = x.max(X_MIN).ln();
    let ln_1mx = (1.0 - x).max(X_MIN).ln();
    let ln_pdf = (a - 1.0) * ln_x + (b - 1.0) * ln_1mx - ln_beta;
    ln_pdf.exp()
}

/// Regularized incomplete beta `I_x(a, b)` via the standard split:
///   - if `x < (a+1)/(a+b+2)`: direct continued fraction (Lentz).
///   - else: use the symmetry `I_x(a,b) = 1 - I_{1-x}(b,a)`.
///
/// Numerical Recipes §6.4 `betai` + `betacf`.
#[inline]
fn reg_inc_beta(x: f32, a: f32, b: f32, ln_beta: f32) -> f32 {
    if x <= 0.0 {
        return 0.0;
    }
    if x >= 1.0 {
        return 1.0;
    }
    // Prefactor `bt = x^a (1-x)^b / B(a,b)` (the NR "front" term).
    // The `/a` (or `/b` in the symmetry branch) is applied by the caller.
    let ln_front = a * x.ln() + b * (1.0 - x).ln() - ln_beta;
    let bt = ln_front.exp();

    let thresh = (a + 1.0) / (a + b + 2.0);
    if x < thresh {
        bt * betacf(x, a, b) / a
    } else {
        // Symmetry: I_x(a,b) = 1 - I_{1-x}(b,a)
        1.0 - bt * betacf(1.0 - x, b, a) / b
    }
}

/// Lentz's continued-fraction evaluation of the standard `betacf` (NR §6.4).
/// Returns `cf` such that `I_x(a,b) = front * cf / a` (when x < thresh) or
/// `1 - front' * cf' / b` (otherwise).
#[inline]
fn betacf(x: f32, a: f32, b: f32) -> f32 {
    let qab = a + b;
    let qap = a + 1.0;
    let qam = a - 1.0;
    let mut c = 1.0_f32;
    let mut d = 1.0_f32 - qab * x / qap;
    if d.abs() < CF_TINY {
        d = CF_TINY;
    }
    d = 1.0 / d;
    let mut h = d;
    let mut m: usize = 1;
    while m < MAX_CF {
        let mf = m as f32;
        let m2 = 2.0 * mf;
        // Even step.
        let aa = mf * (b - mf) * x / ((qam + m2) * (a + m2));
        d = 1.0 + aa * d;
        if d.abs() < CF_TINY {
            d = CF_TINY;
        }
        c = 1.0 + aa / c;
        if c.abs() < CF_TINY {
            c = CF_TINY;
        }
        d = 1.0 / d;
        h *= d * c;
        // Odd step.
        let aa = -(a + mf) * (qab + mf) * x / ((a + m2) * (qap + m2));
        d = 1.0 + aa * d;
        if d.abs() < CF_TINY {
            d = CF_TINY;
        }
        c = 1.0 + aa / c;
        if c.abs() < CF_TINY {
            c = CF_TINY;
        }
        d = 1.0 / d;
        let del = d * c;
        h *= del;
        if (del - 1.0).abs() < CF_TOL {
            break;
        }
        m += 1;
    }
    h
}

/// Bisection fallback when Newton steps out of `(0, 1)` or the pdf underflows.
/// `x_last` is the last in-bounds Newton iterate; we bracket from it.
#[cold]
#[inline(never)]
fn newton_or_bisect(a: f32, b: f32, eps: f32, x_last: f32, ln_beta: f32) -> f32 {
    // Build a bracket `[lo, hi]` with `I_lo < eps < I_hi`. Start from x_last
    // (which is in (X_MIN, X_MAX)) and expand outward.
    let mut lo = X_MIN;
    let mut hi = X_MAX;
    // Tighten the bracket using x_last if it's on the correct side.
    let cdf_last = reg_inc_beta(x_last, a, b, ln_beta);
    if cdf_last < eps {
        lo = x_last;
    } else if cdf_last > eps {
        hi = x_last;
    } else {
        return x_last;
    }

    // Bisection: ~24 iters shrinks (X_MIN, X_MAX) by 2^24 ≈ f32 precision.
    for _ in 0..48 {
        let mid = 0.5 * (lo + hi);
        if mid <= lo || mid >= hi {
            return mid;
        }
        let cdf_mid = reg_inc_beta(mid, a, b, ln_beta);
        if cdf_mid < eps {
            lo = mid;
        } else if cdf_mid > eps {
            hi = mid;
        } else {
            return mid;
        }
        if (hi - lo) < TOL {
            break;
        }
    }
    0.5 * (lo + hi)
}

/// Acklam's rational approximation to the inverse standard normal CDF
/// `Φ⁻¹(p)` for `p ∈ (0, 1)`. Absolute error < 1.15e-9 in f64; well within
/// f32 precision after downcast. Used only for the Newton initial guess, so
/// even its 1e-9 error is negligible (Newton converges from there in ≤ 4 iters
/// for our `a, b ≥ 1` domain).
#[inline]
fn inv_normal_cdf(p: f32) -> f32 {
    // Constants from Acklam (2003). Use f64 internally for the rational form,
    // downcast at the end.
    let p = p as f64;
    let a = [
        -3.969_683_028_665_376e+01_f64,
        2.209_460_984_245_205e+02,
        -2.759_285_104_469_687e+02,
        1.383_577_518_672_69e+02,
        -3.066_479_806_614_716e+01,
        2.506_628_277_459_239e+00,
    ];
    let b = [
        -5.447_609_879_822_406e+01_f64,
        1.615_858_368_580_409e+02,
        -1.556_989_798_598_866e+02,
        6.680_131_188_771_972e+01,
        -1.328_068_155_288_572e+01,
    ];
    let c = [
        -7.784_894_002_430_293e-03_f64,
        -3.223_964_580_411_365e-01,
        -2.400_758_277_161_838e+00,
        -2.549_732_539_343_734e+00,
        4.374_664_141_464_968e+00,
        2.938_163_982_698_783e+00,
    ];
    let d = [
        7.784_695_709_041_462e-03_f64,
        3.224_671_290_700_398e-01,
        2.445_134_137_142_996e+00,
        3.754_408_661_907_416e+00,
    ];

    let plow = 0.02425_f64;
    let phigh = 1.0 - plow;

    let z = if p < plow {
        let q = (-2.0 * p.ln()).sqrt();
        let num = ((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5];
        let den = (((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1.0;
        num / den
    } else if p <= phigh {
        let q = p - 0.5;
        let r = q * q;
        let num = (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) * q;
        let den = ((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1.0;
        num / den
    } else {
        let q = (-2.0 * (1.0 - p).ln()).sqrt();
        let num = ((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5];
        let den = (((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1.0;
        -num / den
    };
    z as f32
}

// ──────────────────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn best_belief_score_monotone_in_successes() {
        // Fix F=5, ε=0.05; more successes → higher (less conservative) lower bound.
        let mut prev = f32::NEG_INFINITY;
        for s in 0..=20u32 {
            let score = best_belief_score(s, 5, 0.05);
            assert!(
                score > prev,
                "monotonicity broken at S={s}: prev={prev}, score={score}"
            );
            prev = score;
        }
    }

    #[test]
    fn best_belief_score_monotone_in_failures_decreasing() {
        // Fix S=10, ε=0.05; fewer failures → higher score.
        let mut prev = f32::NEG_INFINITY;
        for f in (0..=20u32).rev() {
            let score = best_belief_score(10, f, 0.05);
            assert!(
                score > prev,
                "monotonicity broken at F={f}: prev={prev}, score={score}"
            );
            prev = score;
        }
    }

    #[test]
    fn best_belief_score_at_epsilon_half_approximates_mean() {
        // At ε=0.5, the median of Beta(α, β). For α, β > 1 the median ≈ mean
        // α/(α+β). Tolerance 1e-2 (the median-mean gap is small but nonzero
        // for skewed Beta; the spec's 1e-3 is too tight for highly skewed
        // cases like (S=50, F=1) → use a moderate case).
        for &(s, f) in &[(10u32, 10u32), (20, 20), (5, 5)] {
            let score = best_belief_score(s, f, 0.5);
            let alpha = 1.0 + s as f32;
            let beta = 1.0 + f as f32;
            let mean = alpha / (alpha + beta);
            assert!(
                (score - mean).abs() < 1e-2,
                "S={s} F={f}: median {score} too far from mean {mean}"
            );
        }
    }

    #[test]
    fn best_belief_score_lower_epsilon_is_more_conservative() {
        // Same (S, F); ε=0.05 < ε=0.5 → strictly lower score.
        for &(s, f) in &[(10u32, 5u32), (3, 7), (50, 50)] {
            let lo = best_belief_score(s, f, 0.05);
            let hi = best_belief_score(s, f, 0.5);
            assert!(
                lo < hi,
                "lower ε should be more conservative: S={s} F={f}, ε=0.05 → {lo}, ε=0.5 → {hi}"
            );
        }
    }

    #[test]
    fn best_belief_score_bounds() {
        let grid = [0u32, 1, 5, 50];
        let eps_grid = [0.01f32, 0.05, 0.5];
        for &s in &grid {
            for &f in &grid {
                for &eps in &eps_grid {
                    if s == 0 && f == 0 {
                        continue; // tested separately
                    }
                    let score = best_belief_score(s, f, eps);
                    assert!(
                        score > 0.0 && score < 1.0,
                        "S={s} F={f} ε={eps}: score {score} not strictly in (0,1)"
                    );
                }
            }
        }
    }

    #[test]
    fn best_belief_score_uniform_prior() {
        // Beta(1, 1) = Uniform(0, 1); the ε-quantile is ε itself.
        // (The "lower bound the utility exceeds with prob 1-ε" IS ε here.)
        for &eps in &[0.01f32, 0.05, 0.1, 0.5] {
            let score = best_belief_score(0, 0, eps);
            assert!(
                (score - eps).abs() < 1e-6,
                "uniform prior ε-quantile: expected {eps}, got {score}"
            );
        }
    }

    #[test]
    fn select_best_belief_favors_incumbent_on_tie() {
        // Exact tie: two identical candidates. incumbent_idx=Some(1) → 1.
        let candidates: [(u32, u32); 2] = [(10, 5), (10, 5)];
        let winner = select_best_belief(&candidates, 0.05, Some(1));
        assert_eq!(
            winner, 1,
            "incumbent should win the tie (got {winner})"
        );
    }

    #[test]
    fn select_best_belief_picks_higher_lower_bound() {
        // (S=10, F=1) is small-but-confident and should beat (S=100, F=90)
        // large-but-noisy at ε=0.05. This is the conservative property.
        let candidates: [(u32, u32); 2] = [(10, 1), (100, 90)];
        let winner = select_best_belief(&candidates, 0.05, None);
        assert_eq!(
            winner, 0,
            "small-but-confident (10,1) should beat large-but-noisy (100,90) at ε=0.05"
        );
        // Sanity: confirm the actual scores.
        let s0 = best_belief_score(10, 1, 0.05);
        let s1 = best_belief_score(100, 90, 0.05);
        assert!(s0 > s1, "score (10,1)={s0} should exceed (100,90)={s1}");
    }

    #[test]
    fn select_best_belief_with_none_incumbent_picks_argmax() {
        let candidates: [(u32, u32); 3] = [(1, 10), (50, 1), (5, 5)];
        let winner = select_best_belief(&candidates, 0.05, None);
        assert_eq!(winner, 1, "argmax should pick index 1 (50,1)");
    }

    #[test]
    #[should_panic(expected = "empty candidate slice")]
    fn select_best_belief_panics_on_empty() {
        let empty: [(u32, u32); 0] = [];
        let _ = select_best_belief(&empty, 0.05, None);
    }

    #[test]
    fn select_best_belief_incumbent_out_of_range_falls_back_to_argmax() {
        let candidates: [(u32, u32); 2] = [(1, 10), (50, 1)];
        let winner = select_best_belief(&candidates, 0.05, Some(99));
        assert_eq!(
            winner, 1,
            "out-of-range incumbent should fall back to argmax (index 1)"
        );
    }

    #[test]
    fn best_belief_scores_matches_individual_calls() {
        let candidates: [(u32, u32); 4] = [(0, 0), (10, 1), (5, 5), (100, 90)];
        let scores = best_belief_scores(&candidates, 0.05);
        for (i, &(s, f)) in candidates.iter().enumerate() {
            assert_eq!(scores[i], best_belief_score(s, f, 0.05));
        }
    }

    #[test]
    fn best_belief_score_epsilon_clamping() {
        // epsilon ≤ 0 → clamp to EPS_MIN → a very small but still valid score.
        // For Beta(11, 6) (mean ≈ 0.647, σ ≈ 0.11) even the 1e-7 quantile is
        // ~0.06 (≈ mean + σ·Φ⁻¹(1e-7) ≈ 0.647 − 5.2·0.11), NOT < 1e-3. The
        // clamping contract is: result is strictly in (0, 1) AND more
        // conservative than eps = 0.05.
        let score_neg = best_belief_score(10, 5, -1.0);
        assert!(score_neg > 0.0 && score_neg < 1.0);
        let score_005 = best_belief_score(10, 5, 0.05);
        assert!(
            score_neg < score_005,
            "clamped-near-zero ε should be more conservative than ε=0.05: {score_neg} vs {score_005}"
        );
        // epsilon ≥ 1 → clamp to X_MAX (~1.0) directly (upper tail).
        let score_big = best_belief_score(10, 5, 2.0);
        assert!(score_big > 0.999);
    }

    // ── LUT fast-path tests (Plan 336 G2 unblock) ─────────────────────────
    // The LUT must be bit-identical to the closed form for every point it
    // covers, because the LUT is populated by calling the closed form at
    // init time. Any mismatch would indicate a LUT indexing bug.

    #[test]
    fn lut_bit_identical_to_closed_form_across_grid() {
        // Exhaustively check every LUT cell: for each (eps, S, F) in the LUT
        // domain, best_belief_score must equal best_belief_score_cf to the bit.
        for &eps in &LUT_EPS {
            for s in 0..LUT_S as u32 {
                for f in 0..LUT_F as u32 {
                    let via_lut = best_belief_score(s, f, eps);
                    let via_cf = best_belief_score_cf(s, f, eps);
                    assert_eq!(
                        via_lut.to_bits(),
                        via_cf.to_bits(),
                        "LUT mismatch at S={}, F={}, eps={}: lut={}, cf={}",
                        s, f, eps, via_lut, via_cf
                    );
                }
            }
        }
    }

    #[test]
    fn lut_covers_boundary_excluded() {
        // S or F == LUT_S (32) is just outside the LUT — must fall back to CF
        // and still produce a valid, finite answer. Verifies the `>= LUT_S`
        // guard.
        let boundary = best_belief_score(LUT_S as u32, 0, 0.05);
        assert!(boundary.is_finite() && boundary > 0.0 && boundary < 1.0);
        let boundary_f = best_belief_score(0, LUT_F as u32, 0.05);
        assert!(boundary_f.is_finite() && boundary_f > 0.0 && boundary_f < 1.0);
    }

    #[test]
    fn lut_misses_for_nonstandard_epsilon() {
        // ε = 0.07 is not in LUT_EPS → falls back to closed form. The result
        // must still be correct (between the ε=0.05 and ε=0.1 scores, by
        // monotonicity in ε). Note: HIGHER ε → HIGHER quantile → LESS
        // conservative → HIGHER score. So 0.05 < 0.07 < 0.1 implies
        // score(0.05) < score(0.07) < score(0.1).
        let s = 10u32;
        let f = 5u32;
        let off_grid = best_belief_score(s, f, 0.07);
        let e05 = best_belief_score(s, f, 0.05);
        let e10 = best_belief_score(s, f, 0.1);
        assert!(
            off_grid > e05 && off_grid < e10,
            "non-standard ε=0.07 (S={}, F={}) should be between ε=0.05 ({}) and ε=0.1 ({}), got {}",
            s, f, e05, e10, off_grid
        );
    }

    #[test]
    fn lut_handles_all_standard_epsilons() {
        // Smoke test: each of the five standard ε values produces a valid
        // in-(0,1) score for a representative (S, F) inside the LUT.
        for &eps in &LUT_EPS {
            let score = best_belief_score(15, 7, eps);
            assert!(
                score > 0.0 && score < 1.0 && score.is_finite(),
                "LUT score at eps={} invalid: {}",
                eps,
                score
            );
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────
// G1 reference (Phase 2 T2.1) — independent verification vs `statrs`.
//
// `statrs` is a native-only dev-dependency (Cargo.toml target-gated), so this
// module compiles only under `cargo test` on native targets. The grid is
// 8×8×5 = 320 points — small enough that even a slow reference is fine.
// ──────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod statrs_reference {
    use super::*;
    use statrs::distribution::ContinuousCDF;

    // G1 (Plan 336 T2.1): max abs error < 1e-3 vs statrs Beta quantile across
    // a grid. The target is 1e-4 in the plan; we assert 1e-3 for safety and
    // record the actual max_err via eprintln! so it can be captured into the
    // plan's results section.
    #[test]
    fn best_belief_score_matches_statrs_reference() {
        let dist_grid = [0usize, 1, 2, 5, 10, 25, 50, 100];
        let eps_grid = [0.01f32, 0.05, 0.1, 0.25, 0.5];
        let mut max_err = 0.0f32;
        let mut worst: Option<(usize, usize, f32, f32, f32)> = None;
        for &s in &dist_grid {
            for &f in &dist_grid {
                for &eps in &eps_grid {
                    let ours = best_belief_score(s as u32, f as u32, eps);
                    let alpha = 1.0 + s as f64;
                    let beta = 1.0 + f as f64;
                    let beta_dist = statrs::distribution::Beta::new(alpha, beta).unwrap();
                    // statrs 0.17 exposes `inverse_cdf(p)` on ContinuousCDF.
                    let theirs = beta_dist.inverse_cdf(eps as f64) as f32;
                    let err = (ours - theirs).abs();
                    assert!(
                        err < 1e-3,
                        "S={s}, F={f}, eps={eps}: ours={ours}, theirs={theirs}, err={err}",
                    );
                    if err > max_err {
                        max_err = err;
                        worst = Some((s, f, eps, ours, theirs));
                    }
                }
            }
        }
        if let Some((s, f, eps, ours, theirs)) = worst {
            eprintln!(
                "G1 max_err vs statrs = {:.3e}  (worst: S={s}, F={f}, eps={eps}, ours={ours}, theirs={theirs})",
                max_err
            );
        } else {
            eprintln!("G1 max_err vs statrs = 0.0 (no points evaluated?)");
        }
    }
}
