//! ANE batch NPC brain compute — CoreML dispatch for NPC sense projection (Plan 255 Part 3).
//!
//! Loads a pre-compiled `.mlmodelc` CoreML model and runs batch NPC brain
//! evaluations on the Apple Neural Engine. Falls back to `CpuTernaryBackend`
//! if ANE is not resident or model loading fails.
//!
//! # Model I/O
//!
//! The CoreML model (generated by `scripts/generate_npc_brain_model.py`) expects:
//! - **Input 1** `sense_weights`: `[B, MAX_MODULES, HLA_DIM]` — ternary→float weight matrix
//! - **Input 2** `hla_state`: `[B, HLA_DIM]` — HLA state per NPC
//! - **Input 3** `emotion_direction`: `[B, HLA_DIM]` — emotion dot-product direction
//! - **Input 4** `zone_direction`: `[B, HLA_DIM]` — zone dot-product direction
//! - **Input 5** `confidence`: `[B, MAX_MODULES]` — per-module confidence
//!
//! - **Output 1** `sense_proj`: `[B, MAX_MODULES]` — sense projection (sigmoid + confidence)
//! - **Output 2** `emotion_proj`: `[B]` — emotion projection scalar
//! - **Output 3** `zone_proj`: `[B]` — zone projection scalar
//!
//! # Residency Validation
//!
//! At construction, a dummy prediction is timed. If latency > 1ms, the model
//! likely fell back to CPU and construction fails. Caller should use
//! `CpuTernaryBackend` instead.

use coreml_native as coreml;

#[cfg(test)]
use katgpt_core::sense::backend::CpuTernaryBackend;
use katgpt_core::sense::backend::{MAX_MODULES, NpcBrainBackend, NpcBrainInput, NpcBrainOutput};

#[cfg(test)]
use katgpt_core::types::TernaryDir;

/// HLA state dimensionality (matches `NpcBrainInput::hla_state`).
const HLA_DIM: usize = 8;

/// ANE residency threshold — predictions slower than this indicate CPU fallback.
const RESIDENCY_THRESHOLD_US: u64 = 1000;

/// Default optimal batch size for ANE dispatch.
/// ANE works best with larger batches due to fixed dispatch overhead.
const OPTIMAL_BATCH_SIZE: usize = 1024;

// ── Input encoding constants ────────────────────────────────────────────────
//
// The CoreML model expects sense_weights as a float weight matrix where
// ternary directions are converted to float values. Each TernaryDir encodes
// a single row: for dimension i, pos_bit=1 → +1.0, neg_bit=1 → -1.0, else 0.0.
// The row_scale is applied per-direction-row.

/// ANE NPC brain backend using Apple CoreML framework.
///
/// Wraps a pre-compiled CoreML model for batch NPC sense projection.
/// The model is loaded from a `.mlmodelc` file at construction time.
pub struct AneNpcBrainBackend {
    model: coreml::Model,
    /// Maximum batch size (model may be compiled for a fixed shape).
    max_batch_size: usize,
    /// Discovered name of the sense projection output (`[B, MAX_MODULES]`).
    ///
    /// CoreML `ct.convert()` auto names outputs (`mul_0`, `sigmoid_1`, ...),
    /// so we discover the name at construction by inspecting `model.outputs()`
    /// rather than hardcoding it.
    sense_output_name: String,
    /// Reusable padded-input buffer (sized to max_batch_size).
    /// Eliminates per-call Vec allocation when batch < max_batch_size.
    padded_inputs: Vec<NpcBrainInput>,
    /// Reusable encoded tensor scratch buffers.
    /// Avoids 5 heap allocations per batch_evaluate() call.
    scratch_sense_weights: Vec<f32>,
    scratch_hla_state: Vec<f32>,
    scratch_emotion_dir: Vec<f32>,
    scratch_zone_dir: Vec<f32>,
    scratch_confidence: Vec<f32>,
}

/// Error type for ANE NPC brain backend operations.
#[derive(Debug)]
pub enum AneNpcError {
    /// CoreML model loading failed.
    ModelLoad(String),
    /// CoreML prediction failed.
    Prediction(String),
    /// ANE residency check failed (model fell back to CPU).
    ResidencyFailed { latency_us: u64, threshold_us: u64 },
    /// I/O error loading model file.
    Io(std::io::Error),
    /// Input encoding error (e.g., batch too large).
    Encoding(String),
}

impl std::fmt::Display for AneNpcError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ModelLoad(msg) => write!(f, "ANE NPC model load error: {msg}"),
            Self::Prediction(msg) => write!(f, "ANE NPC prediction error: {msg}"),
            Self::ResidencyFailed {
                latency_us,
                threshold_us,
            } => write!(
                f,
                "ANE residency check failed: {latency_us}μs > {threshold_us}μs (model fell back to CPU)"
            ),
            Self::Io(e) => write!(f, "I/O error: {e}"),
            Self::Encoding(msg) => write!(f, "input encoding error: {msg}"),
        }
    }
}

impl std::error::Error for AneNpcError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(e) => Some(e),
            _ => None,
        }
    }
}

impl AneNpcBrainBackend {
    /// Create a new ANE NPC brain backend by loading a CoreML model.
    ///
    /// Accepts either:
    /// - `.mlmodelc` — pre-compiled bundle, loaded directly (fast).
    /// - `.mlpackage` / `.mlmodel` — source spec, compiled to `.mlmodelc` first
    ///   via `MLModel::compileModel(at:)` (one-time ~1-5s, result in temp dir).
    ///
    /// After loading, runs a residency validation: a dummy prediction is timed
    /// and if latency exceeds 1ms, returns `AneNpcError::ResidencyFailed`.
    /// This catches cases where CoreML silently falls back to CPU.
    pub fn new(path: &std::path::Path, max_batch_size: usize) -> Result<Self, AneNpcError> {
        let compiled_path = Self::ensure_compiled(path)?;
        let model = coreml::Model::load(&compiled_path, coreml::ComputeUnits::All)
            .map_err(|e| AneNpcError::ModelLoad(format!("load: {e}")))?;

        // Discover the sense projection output name. CoreML's `ct.convert()`
        // generates MIL-derived names (e.g. `mul_0`), not the Python variable
        // names, so we inspect the model description and pick the first
        // MultiArray output — that's the `[B, MAX_MODULES]` sense projection.
        // (The other two outputs are `[B, 1]` scalars; we currently only
        // consume the sense projection and apply overrides/autonomous-disabled
        // on the Rust side.)
        let sense_output_name = model
            .outputs()
            .iter()
            .find(|d| matches!(d.feature_type(), coreml::FeatureType::MultiArray))
            .map(|d| d.name().to_string())
            .ok_or_else(|| {
                AneNpcError::ModelLoad("no MultiArray output found in model".into())
            })?;
        log::info!("ANE NPC brain: sense output name = '{sense_output_name}'");

        // Query the model's compiled batch size from the hla_state input shape.
        // Fixed-shape ANE models reject any other batch size, so the compiled
        // value wins over the caller's `max_batch_size` hint.
        let model_batch = model
            .inputs()
            .iter()
            .find(|d| d.name() == "hla_state")
            .and_then(|d| d.shape())
            .and_then(|s| s.first().copied())
            .unwrap_or(max_batch_size);
        if model_batch != max_batch_size {
            log::info!(
                "ANE NPC brain: model compiled batch={model_batch} overrides caller hint={max_batch_size}"
            );
        }

        let backend = Self {
            model,
            max_batch_size: model_batch,
            sense_output_name,
            padded_inputs: vec![NpcBrainInput::default(); model_batch],
            scratch_sense_weights: vec![0.0f32; model_batch * MAX_MODULES * HLA_DIM],
            scratch_hla_state: vec![0.0f32; model_batch * HLA_DIM],
            scratch_emotion_dir: vec![0.0f32; model_batch * HLA_DIM],
            scratch_zone_dir: vec![0.0f32; model_batch * HLA_DIM],
            scratch_confidence: vec![0.0f32; model_batch * MAX_MODULES],
        };

        // Validate ANE residency at the model's compiled batch size
        backend.validate_residency()?;

        Ok(backend)
    }

    /// Return a `.mlmodelc` path for the given source.
    ///
    /// - `.mlmodelc` → returned as-is.
    /// - `.mlpackage` / `.mlmodel` → compiled to a temp `.mlmodelc` via CoreML.
    ///
    /// The compiled model lands in CoreML's temp dir; the path is owned by the
    /// system and remains valid for the process lifetime. Callers that want
    /// persistence should ship `.mlmodelc` directly.
    fn ensure_compiled(path: &std::path::Path) -> Result<std::path::PathBuf, AneNpcError> {
        let is_compiled = path
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| e == "mlmodelc")
            .unwrap_or(false);

        if is_compiled {
            return Ok(path.to_path_buf());
        }

        log::info!(
            "ANE NPC brain: compiling {} → .mlmodelc (one-time)",
            path.display()
        );
        let compiled = coreml::compile_model(path)
            .map_err(|e| AneNpcError::ModelLoad(format!("compile {}: {e}", path.display())))?;
        log::info!("ANE NPC brain: compiled → {}", compiled.display());
        Ok(compiled)
    }

    /// Validate ANE residency by timing dummy predictions after warmup.
    ///
    /// Creates dummy inputs sized to `max_batch_size` (the model's compiled
    /// batch), runs a few warmup predictions to stabilize the ANE pipeline
    /// (first run includes compile overhead), then times a final prediction.
    /// ANE predictions are typically <100µs for this model; CPU fallback is >5ms.
    fn validate_residency(&self) -> Result<(), AneNpcError> {
        const RESIDENCY_WARMUP: usize = 3;
        let batch = self.max_batch_size;

        // Allocate dummy inputs at the model's compiled batch size
        let sense_weights = vec![0.0f32; batch * MAX_MODULES * HLA_DIM];
        let hla_state = vec![1.0f32; batch * HLA_DIM];
        let emotion_dir = vec![0.5f32; batch * HLA_DIM];
        let zone_dir = vec![0.5f32; batch * HLA_DIM];
        let confidence = vec![1.0f32; batch * MAX_MODULES];

        // Warmup: first prediction triggers ANE pipeline compilation (~ms-scale).
        for _ in 0..RESIDENCY_WARMUP {
            let _ = self.predict_raw(
                batch,
                &sense_weights,
                &hla_state,
                &emotion_dir,
                &zone_dir,
                &confidence,
            )?;
        }

        // Timed prediction — should now reflect steady-state ANE dispatch.
        let start = std::time::Instant::now();
        self.predict_raw(
            batch,
            &sense_weights,
            &hla_state,
            &emotion_dir,
            &zone_dir,
            &confidence,
        )?;
        let elapsed_us = start.elapsed().as_micros() as u64;

        if elapsed_us > RESIDENCY_THRESHOLD_US {
            return Err(AneNpcError::ResidencyFailed {
                latency_us: elapsed_us,
                threshold_us: RESIDENCY_THRESHOLD_US,
            });
        }

        log::info!(
            "ANE NPC brain backend: residency OK ({elapsed_us}μs < {RESIDENCY_THRESHOLD_US}μs)"
        );
        Ok(())
    }

    /// Run a raw CoreML prediction with pre-encoded batch tensors.
    ///
    /// Returns the prediction result for output extraction.
    fn predict_raw(
        &self,
        batch: usize,
        sense_weights: &[f32],
        hla_state: &[f32],
        emotion_dir: &[f32],
        zone_dir: &[f32],
        confidence: &[f32],
    ) -> Result<coreml::Prediction, AneNpcError> {
        let sw_tensor =
            coreml::BorrowedTensor::from_f32(sense_weights, &[batch, MAX_MODULES, HLA_DIM])
                .map_err(|e| AneNpcError::Prediction(format!("sense_weights tensor: {e}")))?;

        let hla_tensor = coreml::BorrowedTensor::from_f32(hla_state, &[batch, HLA_DIM])
            .map_err(|e| AneNpcError::Prediction(format!("hla_state tensor: {e}")))?;

        let emo_tensor = coreml::BorrowedTensor::from_f32(emotion_dir, &[batch, HLA_DIM])
            .map_err(|e| AneNpcError::Prediction(format!("emotion_direction tensor: {e}")))?;

        let zone_tensor = coreml::BorrowedTensor::from_f32(zone_dir, &[batch, HLA_DIM])
            .map_err(|e| AneNpcError::Prediction(format!("zone_direction tensor: {e}")))?;

        let conf_tensor = coreml::BorrowedTensor::from_f32(confidence, &[batch, MAX_MODULES])
            .map_err(|e| AneNpcError::Prediction(format!("confidence tensor: {e}")))?;

        let prediction = self
            .model
            .predict(&[
                ("sense_weights", &sw_tensor as &dyn coreml::AsMultiArray),
                ("hla_state", &hla_tensor as &dyn coreml::AsMultiArray),
                (
                    "emotion_direction",
                    &emo_tensor as &dyn coreml::AsMultiArray,
                ),
                ("zone_direction", &zone_tensor as &dyn coreml::AsMultiArray),
                ("confidence", &conf_tensor as &dyn coreml::AsMultiArray),
            ])
            .map_err(|e| AneNpcError::Prediction(format!("predict: {e}")))?;

        Ok(prediction)
    }
}

/// Encode all NPC brain inputs into CoreML batch tensors, writing into
/// caller-provided scratch buffers (zero per-call allocation).
///
/// Writes sense_weights `[B, MAX_MODULES, HLA_DIM]`, hla_state `[B, HLA_DIM]`,
/// emotion_dir `[B, HLA_DIM]`, zone_dir `[B, HLA_DIM]`, and confidence
/// `[B, MAX_MODULES]` in row-major order.
///
/// `sense_weights[m][i]` encodes the DIAGONAL ternary projection (matches
/// `SenseModule::project`): direction `i` contributes `sign_i * row_scale`
/// at hla dim `i`, where `sign_i` is extracted from bit `i` of `directions[i]`.
#[allow(clippy::too_many_arguments)]
fn encode_batch_into(
    inputs: &[NpcBrainInput],
    sense_weights: &mut [f32],
    hla_state: &mut [f32],
    emotion_dir: &mut [f32],
    zone_dir: &mut [f32],
    confidence: &mut [f32],
) {
    let batch = inputs.len();

    // Zero all output buffers once so unused slots (padding rows, dims ≥ n_directions)
    // don't carry stale data from the previous call.
    let sw_len = batch * MAX_MODULES * HLA_DIM;
    let hla_len = batch * HLA_DIM;
    let conf_len = batch * MAX_MODULES;
    sense_weights[..sw_len].fill(0.0);
    hla_state[..hla_len].fill(0.0);
    emotion_dir[..hla_len].fill(0.0);
    zone_dir[..hla_len].fill(0.0);
    confidence[..conf_len].fill(0.0);

    for (b, input) in inputs.iter().enumerate() {
        // HLA state
        let hla_base = b * HLA_DIM;
        hla_state[hla_base..hla_base + HLA_DIM].copy_from_slice(&input.hla_state);

        for m in 0..input.module_count {
            let module = &input.modules[m];

            // Encode the DIAGONAL ternary projection that matches `SenseModule::project`:
            //   dot = Σ_{i=0}^{n-1} sign_i(directions[i]) * hla_state[i] * row_scale[i]
            // where sign_i extracts bit `i` of `directions[i]`'s pos/neg bitfield.
            //
            // This is NOT a full matvec — direction `i` only touches hla dim `i`.
            // We encode it as `sense_weights[m][i] = sign_i * row_scale[i]` so that
            // the model's `dot(sense_weights[m], hla_state)` reproduces the same sum.
            // Dims ≥ n_directions are zero (no contribution).
            let module_base = (b * MAX_MODULES + m) * HLA_DIM;
            let n = module.n_directions as usize;
            for i in 0..n {
                let dir = &module.directions[i];
                let pos = ((dir.pos_bits >> i) & 1) as i8 as f32;
                let neg = ((dir.neg_bits >> i) & 1) as i8 as f32;
                sense_weights[module_base + i] = (pos - neg) * dir.row_scale;
            }

            // Confidence
            confidence[b * MAX_MODULES + m] = module.confidence;

            // Emotion direction: use module 0's diagonal as emotion proxy
            if m == 0 && n > 0 {
                for i in 0..n {
                    let dir = &module.directions[i];
                    let pos = ((dir.pos_bits >> i) & 1) as i8 as f32;
                    let neg = ((dir.neg_bits >> i) & 1) as i8 as f32;
                    emotion_dir[hla_base + i] = (pos - neg) * dir.row_scale;
                }
            }

            // Zone direction: use module 1's diagonal as zone proxy
            if m == 1 && n > 0 {
                for i in 0..n {
                    let dir = &module.directions[i];
                    let pos = ((dir.pos_bits >> i) & 1) as i8 as f32;
                    let neg = ((dir.neg_bits >> i) & 1) as i8 as f32;
                    zone_dir[hla_base + i] = (pos - neg) * dir.row_scale;
                }
            }
        }
    }
}

/// Decode the CoreML prediction output into `NpcBrainOutput` values.
///
/// Reads the sense projection output tensor (`sense_output_name`, which is
/// discovered at construction since CoreML auto-names it) and fills `outputs`.
/// GM overrides and autonomous_disabled are applied after decoding
/// (matching `CpuTernaryBackend` semantics).
fn decode_output(
    prediction: &coreml::Prediction,
    sense_output_name: &str,
    inputs: &[NpcBrainInput],
    outputs: &mut [NpcBrainOutput],
) -> Result<(), AneNpcError> {
    let batch = inputs.len();

    // Extract sense projection output: [B, MAX_MODULES]
    let (sense_data, _shape) = prediction
        .get_f32(sense_output_name)
        .map_err(|e| AneNpcError::Prediction(format!("get {sense_output_name}: {e}")))?;

    for b in 0..batch {
        let projections = &mut outputs[b].projections;
        *projections = [0.0; MAX_MODULES];

        let module_count = inputs[b].module_count;
        let autonomous_disabled = inputs[b].autonomous_disabled;

        for m in 0..module_count {
            // Check GM override first (matches CpuTernaryBackend priority)
            if let Some(v) = inputs[b].overrides[m] {
                projections[m] = v;
                continue;
            }
            if autonomous_disabled {
                // Already zeroed above
                continue;
            }

            // Use the ANE-computed projection
            let idx = b * MAX_MODULES + m;
            if idx < sense_data.len() {
                projections[m] = sense_data[idx];
            }
        }
    }

    Ok(())
}

impl NpcBrainBackend for AneNpcBrainBackend {
    fn batch_evaluate(
        &mut self,
        inputs: &[NpcBrainInput],
        outputs: &mut [NpcBrainOutput],
    ) -> Result<(), String> {
        if inputs.len() != outputs.len() {
            return Err(format!(
                "input/output length mismatch: {} vs {}",
                inputs.len(),
                outputs.len()
            ));
        }

        if inputs.is_empty() {
            return Ok(());
        }

        let batch = inputs.len();
        if batch > self.max_batch_size {
            return Err(format!(
                "batch size {batch} exceeds max_batch_size {}",
                self.max_batch_size
            ));
        }

        // Fixed-shape ANE models require the exact compiled batch size.
        // Pad with default (zero) inputs up to max_batch_size, run the full
        // batch, then decode only the first `batch` outputs.
        // This wastes some ANE cycles on padding but avoids dynamic-shape
        // pitfalls (CoreML's RangeDim support is unreliable for ANE).
        //
        // Reuse the cached `padded_inputs` buffer to avoid per-call Vec
        // allocation. The buffer is sized to max_batch_size at construction.
        // `NpcBrainInput` is `Clone` but not `Copy` (it owns arrays), so use
        // `clone_from_slice` rather than `copy_from_slice`.
        if batch < self.max_batch_size {
            self.padded_inputs[..batch].clone_from_slice(inputs);
            // Restore any padding slots that may have been overwritten by a
            // prior, larger (but still sub-max) batch.
            for slot in &mut self.padded_inputs[batch..self.max_batch_size] {
                *slot = NpcBrainInput::default();
            }
        } else {
            // Full batch — write directly. (The slice is exactly max_batch_size.)
            self.padded_inputs.clone_from_slice(inputs);
        }

        // Encode padded inputs into cached scratch tensors (zero alloc).
        encode_batch_into(
            &self.padded_inputs,
            &mut self.scratch_sense_weights,
            &mut self.scratch_hla_state,
            &mut self.scratch_emotion_dir,
            &mut self.scratch_zone_dir,
            &mut self.scratch_confidence,
        );

        // Run prediction on the full padded batch
        let prediction = self
            .predict_raw(
                self.max_batch_size,
                &self.scratch_sense_weights,
                &self.scratch_hla_state,
                &self.scratch_emotion_dir,
                &self.scratch_zone_dir,
                &self.scratch_confidence,
            )
            .map_err(|e| format!("ANE prediction failed: {e}"))?;

        // Decode only the first `batch` outputs (padding rows are discarded)
        decode_output(&prediction, &self.sense_output_name, inputs, outputs)
            .map_err(|e| format!("ANE output decode failed: {e}"))
    }

    fn backend_name(&self) -> &'static str {
        "ane_coreml"
    }

    fn optimal_batch_size(&self) -> usize {
        OPTIMAL_BATCH_SIZE
    }
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_backend_name() {
        // Can't create AneNpcBrainBackend without a model file,
        // but we can verify the constant.
        assert_eq!("ane_coreml", "ane_coreml");
    }

    #[test]
    fn test_optimal_batch_size_constant() {
        assert_eq!(OPTIMAL_BATCH_SIZE, 1024);
    }

    #[test]
    fn test_residency_threshold_constant() {
        assert_eq!(RESIDENCY_THRESHOLD_US, 1000);
    }

    #[test]
    fn test_encode_batch_empty() {
        let inputs: Vec<NpcBrainInput> = vec![NpcBrainInput::default()];
        let batch = inputs.len();
        let mut sense_weights = vec![0.0f32; batch * MAX_MODULES * HLA_DIM];
        let mut hla_state = vec![0.0f32; batch * HLA_DIM];
        let mut emotion_dir = vec![0.0f32; batch * HLA_DIM];
        let mut zone_dir = vec![0.0f32; batch * HLA_DIM];
        let mut confidence = vec![0.0f32; batch * MAX_MODULES];
        encode_batch_into(
            &inputs,
            &mut sense_weights,
            &mut hla_state,
            &mut emotion_dir,
            &mut zone_dir,
            &mut confidence,
        );

        // Default input has module_count=0, all hla_state zero
        assert_eq!(hla_state.len(), HLA_DIM);
        assert!(sense_weights.iter().all(|&v| v == 0.0));
        assert!(hla_state.iter().all(|&v| v == 0.0));
        assert!(confidence.iter().all(|&v| v == 0.0));
    }

    #[test]
    fn test_encode_batch_with_hla_state() {
        let mut input = NpcBrainInput::default();
        input.hla_state = [1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 0.0];
        let inputs = [input];
        let batch = inputs.len();
        let mut sense_weights = vec![0.0f32; batch * MAX_MODULES * HLA_DIM];
        let mut hla_state = vec![0.0f32; batch * HLA_DIM];
        let mut emotion_dir = vec![0.0f32; batch * HLA_DIM];
        let mut zone_dir = vec![0.0f32; batch * HLA_DIM];
        let mut confidence = vec![0.0f32; batch * MAX_MODULES];
        encode_batch_into(
            &inputs,
            &mut sense_weights,
            &mut hla_state,
            &mut emotion_dir,
            &mut zone_dir,
            &mut confidence,
        );

        assert_eq!(hla_state[0], 1.0);
        assert_eq!(hla_state[1], 2.0);
        assert_eq!(hla_state[2], 3.0);
        assert_eq!(hla_state[3], 4.0);
    }

    /// Verify the diagonal sense_weights encoding matches `SenseModule::project`:
    /// direction `i` contributes only at hla dim `i`, using bit `i` of `directions[i]`.
    #[test]
    fn test_encode_batch_diagonal_matches_cpu_projection() {
        use katgpt_core::sense::backend::ModuleInput;

        // Two directions: dir[0] sets bit 0 positive; dir[1] sets bit 1 negative.
        let mut input = NpcBrainInput::default();
        input.hla_state = [0.5, 0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
        input.module_count = 1;
        let mut dirs = [TernaryDir::zero(); 8];
        dirs[0] = TernaryDir { pos_bits: 1 << 0, neg_bits: 0, row_scale: 2.0 };
        dirs[1] = TernaryDir { pos_bits: 0, neg_bits: 1 << 1, row_scale: 4.0 };
        input.modules[0] = ModuleInput { directions: dirs, n_directions: 2, confidence: 1.0 };

        let inputs = [input];
        let batch = inputs.len();
        let mut sense_weights = vec![0.0f32; batch * MAX_MODULES * HLA_DIM];
        let mut hla_state = vec![0.0f32; batch * HLA_DIM];
        let mut emotion_dir = vec![0.0f32; batch * HLA_DIM];
        let mut zone_dir = vec![0.0f32; batch * HLA_DIM];
        let mut confidence = vec![0.0f32; batch * MAX_MODULES];
        encode_batch_into(
            &inputs,
            &mut sense_weights,
            &mut hla_state,
            &mut emotion_dir,
            &mut zone_dir,
            &mut confidence,
        );

        // Module 0, dim 0: sign = +1 (bit 0 of dirs[0] = pos), scale 2.0 → +2.0
        assert_eq!(sense_weights[0], 2.0);
        // Module 0, dim 1: sign = -1 (bit 1 of dirs[1] = neg), scale 4.0 → -4.0
        assert_eq!(sense_weights[1], -4.0);
        // Dims ≥ n_directions are zero
        assert_eq!(sense_weights[2], 0.0);
        assert_eq!(sense_weights[7], 0.0);

        // The model dot(sense_weights[0], hla_state) should equal the CPU's dot:
        //   2.0*0.5 + (-4.0)*0.25 = 1.0 - 1.0 = 0.0 → sigmoid(0)=0.5
        let dot: f32 = sense_weights[..HLA_DIM]
            .iter()
            .zip(hla_state[..HLA_DIM].iter())
            .map(|(w, h)| w * h)
            .sum();
        assert!((dot - 0.0).abs() < 1e-6, "dot = {dot}");
    }

    #[test]
    fn test_ane_error_display() {
        let e = AneNpcError::ModelLoad("not found".into());
        assert!(e.to_string().contains("not found"));

        let e = AneNpcError::Prediction("timeout".into());
        assert!(e.to_string().contains("timeout"));

        let e = AneNpcError::ResidencyFailed {
            latency_us: 5000,
            threshold_us: 1000,
        };
        assert!(e.to_string().contains("5000μs"));
        assert!(e.to_string().contains("1000μs"));
    }

    #[test]
    fn test_length_mismatch_error() {
        // Test the NpcBrainBackend trait method indirectly through CpuTernaryBackend
        // (AneNpcBrainBackend can't be created without model file)
        let mut cpu = CpuTernaryBackend::new();
        let inputs = vec![NpcBrainInput::default(); 2];
        let mut outputs = vec![NpcBrainOutput::default(); 3];
        let result = cpu.batch_evaluate(&inputs, &mut outputs);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("mismatch"));
    }

    /// Test construction when model file exists.
    /// Skipped if the .mlpackage is not available.
    #[test]
    fn test_construction_with_model() {
        let model_path = std::path::Path::new("npc_brain.mlpackage");
        if !model_path.exists() {
            eprintln!("SKIP: npc_brain.mlpackage not found");
            return;
        }

        match AneNpcBrainBackend::new(model_path, 1024) {
            Ok(backend) => {
                assert_eq!(backend.backend_name(), "ane_coreml");
                assert_eq!(backend.optimal_batch_size(), 1024);
            }
            Err(AneNpcError::ResidencyFailed { .. }) => {
                // Model loaded but ANE not resident — this is expected
                // on some hardware configurations
                eprintln!("SKIP: ANE residency check failed (CPU fallback)");
            }
            Err(e) => {
                // Model load failed — unexpected if file exists
                panic!("Model load failed unexpectedly: {e}");
            }
        }
    }

    /// Test batch_evaluate matches CpuTernaryBackend output (cosine ≥ 0.99).
    /// Skipped if model file is not available.
    #[test]
    fn test_matches_cpu_ternary() {
        let model_path = std::path::Path::new("npc_brain.mlpackage");
        if !model_path.exists() {
            eprintln!("SKIP: npc_brain.mlpackage not found");
            return;
        }

        let mut ane = match AneNpcBrainBackend::new(model_path, 1024) {
            Ok(b) => b,
            Err(_) => {
                eprintln!("SKIP: ANE backend not available");
                return;
            }
        };

        // Create test inputs with known ternary directions
        let mut input = NpcBrainInput::default();
        input.hla_state = [1.0, 0.5, -0.5, 0.0, 0.3, -0.1, 0.7, -0.3];
        input.module_count = 2;
        input.modules[0] = katgpt_core::sense::backend::ModuleInput {
            directions: {
                let mut dirs = [TernaryDir::zero(); 8];
                dirs[0] = TernaryDir {
                    pos_bits: 0b0101,
                    neg_bits: 0b1000,
                    row_scale: 1.0,
                };
                dirs
            },
            n_directions: 1,
            confidence: 0.9,
        };
        input.modules[1] = katgpt_core::sense::backend::ModuleInput {
            directions: {
                let mut dirs = [TernaryDir::zero(); 8];
                dirs[0] = TernaryDir {
                    pos_bits: 0b0011,
                    neg_bits: 0b0100,
                    row_scale: 0.5,
                };
                dirs
            },
            n_directions: 1,
            confidence: 0.7,
        };

        let inputs = vec![input];

        // Run CPU baseline
        let mut cpu = CpuTernaryBackend::new();
        let mut cpu_output = vec![NpcBrainOutput::default(); 1];
        cpu.batch_evaluate(&inputs, &mut cpu_output).unwrap();

        // Run ANE
        let mut ane_output = vec![NpcBrainOutput::default(); 1];
        match ane.batch_evaluate(&inputs, &mut ane_output) {
            Ok(()) => {
                // Compare: ANE uses float weights, CPU uses exact ternary.
                // Expect high cosine similarity (≥ 0.99) but not exact match.
                let cosine =
                    cosine_similarity(&cpu_output[0].projections, &ane_output[0].projections);
                assert!(
                    cosine >= 0.99,
                    "ANE/CPU cosine similarity too low: {cosine:.6}\n  CPU: {:?}\n  ANE: {:?}",
                    cpu_output[0].projections,
                    ane_output[0].projections,
                );
            }
            Err(e) => {
                // ANE prediction failed — log but don't fail test
                // (this can happen if model shape doesn't match)
                eprintln!("WARN: ANE prediction failed: {e}");
            }
        }
    }

    /// Cosine similarity between two f32 slices.
    fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
        let dot: f32 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
        let mag_a: f32 = a.iter().map(|x| x * x).sum::<f32>().sqrt();
        let mag_b: f32 = b.iter().map(|x| x * x).sum::<f32>().sqrt();
        dot / (mag_a * mag_b + 1e-8)
    }
}
